FROM appdynamics/ecommerce-java:oracle-java7

# set timezone to UTC
RUN mv /etc/localtime /etc/localtime.bak
RUN ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime

# Install Gradle
RUN curl -O http://downloads.gradle.org/distributions/gradle-2.12-bin.zip
RUN unzip -q gradle-2.12-bin.zip -d /opt/
RUN rm gradle-2.12-bin.zip
ENV GRADLE_HOME /opt/gradle-2.12
ENV PATH $PATH:$GRADLE_HOME/bin
ENV CLIENT_HOME /opt/fulfillment-client

# Copy ECommerce-Java project from build dir
ADD ECommerce-Java /ECommerce-Java

# Gradle build
RUN cd /ECommerce-Java; gradle uberJar; mkdir ${CLIENT_HOME}; cp /ECommerce-Java/ECommerce-FulfillmentClient/build/libs/ECommerce-FulfillmentClient.jar ${CLIENT_HOME}; rm -rf /ECommerce-Java;

# App Server Agent Install
ADD AppServerAgent.zip /

RUN unzip -q /AppServerAgent.zip -d ${CLIENT_HOME}/appagent;rm AppServerAgent.zip
ADD custom-interceptors.xml ${CLIENT_HOME}/appagent/conf/

# (Placeholder - build script will update with zip/rpm directives)
# Machine Agent Install

# Analytics Agent config
ADD configAnalytics.sh /

# Startup scripts
ADD startup.sh /
ADD env.sh /

ADD start-machine-agent.sh /
ADD start-appserver-agent.sh /

RUN chmod +x /startup.sh
RUN chmod +x /env.sh
RUN chmod +x /start-machine-agent.sh
RUN chmod +x /start-appserver-agent.sh
RUN chmod +x /configAnalytics.sh

WORKDIR /
CMD ["/bin/bash","/startup.sh"]

EXPOSE 80
EXPOSE 8080
EXPOSE 8009
