#! /bin/bash
export PROXY_LOG=`ls /opt/appdynamics/appdynamics-sdk-native/logs | grep proxy.*`
if [ -z "${PROXY_LOG}" ]; then
    echo "Error: AppDynamics Native SDK Proxy log not found"
else
    tail -f ${PROXY_LOG}
fi
