# RPM Machine Agent Install
ENV MACHINE_AGENT_HOME /opt/appdynamics/machine-agent
ADD machineagent.rpm /
RUN rpm -i /machineagent.rpm; rm /machineagent.rpm
RUN echo "export MACHINE_AGENT_HOME=${MACHINE_AGENT_HOME}" >> /env.sh
